/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class AnomalyModelMetadataClusters {
    /**
    * Center of each cluster (one value per axis)
    */
    'center': Array<number>;
    /**
    * Size of the cluster
    */
    'maxError': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "center",
            "baseName": "center",
            "type": "Array<number>"
        },
        {
            "name": "maxError",
            "baseName": "maxError",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AnomalyModelMetadataClusters.attributeTypeMap;
    }
}

