/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DspTrainedFeaturesResponseAllOfData } from './dspTrainedFeaturesResponseAllOfData';

export class DspTrainedFeaturesResponseAllOf {
    /**
    * Total number of windows in the data set
    */
    'totalSampleCount': number;
    'data': Array<DspTrainedFeaturesResponseAllOfData>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "totalSampleCount",
            "baseName": "totalSampleCount",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<DspTrainedFeaturesResponseAllOfData>"
        }    ];

    static getAttributeTypeMap() {
        return DspTrainedFeaturesResponseAllOf.attributeTypeMap;
    }
}

