/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApplicationTestingRawDetection } from './applicationTestingRawDetection';

export class GetApplicationTestingRawResultResponseAllOf {
    'detections': Array<ApplicationTestingRawDetection>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "detections",
            "baseName": "detections",
            "type": "Array<ApplicationTestingRawDetection>"
        }    ];

    static getAttributeTypeMap() {
        return GetApplicationTestingRawResultResponseAllOf.attributeTypeMap;
    }
}

