/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GenericApiResponse } from './genericApiResponse';
import { GetUserResponseAllOf } from './getUserResponseAllOf';
import { GetUserResponseAllOfOrganizations } from './getUserResponseAllOfOrganizations';
import { Project } from './project';
import { User } from './user';

export class GetUserResponse {
    /**
    * Whether the operation succeeded
    */
    'success': boolean;
    /**
    * Optional error description (set if \'success\' was false)
    */
    'error'?: string;
    'id': number;
    'username': string;
    'name': string;
    'photo'?: string;
    'created': Date;
    'isEdgeImpulseStaff': boolean;
    'email': string;
    'activated': boolean;
    /**
    * Organizations that the user is a member of. Only filled when requesting information about yourself.
    */
    'organizations': Array<GetUserResponseAllOfOrganizations>;
    'projects': Array<Project>;
    /**
    * Experiments that the user has access to
    */
    'experiments': object;
    /**
    * Whether this is an ephemeral evaluation account.
    */
    'evaluation'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "photo",
            "baseName": "photo",
            "type": "string"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "isEdgeImpulseStaff",
            "baseName": "isEdgeImpulseStaff",
            "type": "boolean"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "activated",
            "baseName": "activated",
            "type": "boolean"
        },
        {
            "name": "organizations",
            "baseName": "organizations",
            "type": "Array<GetUserResponseAllOfOrganizations>"
        },
        {
            "name": "projects",
            "baseName": "projects",
            "type": "Array<Project>"
        },
        {
            "name": "experiments",
            "baseName": "experiments",
            "type": "object"
        },
        {
            "name": "evaluation",
            "baseName": "evaluation",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return GetUserResponse.attributeTypeMap;
    }
}

