/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class SampleFeaturesRequest {
    /**
    * Which feature indices to include (by index)
    */
    'featureIxes': Array<number>;
    'allowDimensionalityReduction': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "featureIxes",
            "baseName": "featureIxes",
            "type": "Array<number>"
        },
        {
            "name": "allowDimensionalityReduction",
            "baseName": "allowDimensionalityReduction",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return SampleFeaturesRequest.attributeTypeMap;
    }
}

