/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class UpdateOrganizationCreateProjectRequest {
    /**
    * Number of transformation jobs that can be ran in parallel
    */
    'transformationParallel'?: number;
    /**
    * List of user IDs to notify when a Job succeeds
    */
    'emailRecipientUids'?: Array<number>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "transformationParallel",
            "baseName": "transformationParallel",
            "type": "number"
        },
        {
            "name": "emailRecipientUids",
            "baseName": "emailRecipientUids",
            "type": "Array<number>"
        }    ];

    static getAttributeTypeMap() {
        return UpdateOrganizationCreateProjectRequest.attributeTypeMap;
    }
}

