/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ActorProjectApiKeyAllOf } from './actorProjectApiKeyAllOf';
import { CreatedUpdatedByUser } from './createdUpdatedByUser';
import { ProjectApiKey } from './projectApiKey';
import { ProjectApiKeyLastUsed } from './projectApiKeyLastUsed';

export class ActorProjectApiKey {
    'id': number;
    'apiKey': string;
    'isDevelopmentKey': boolean;
    'name': string;
    'created': Date;
    'role': ActorProjectApiKeyRoleEnum;
    'createdByUser'?: CreatedUpdatedByUser;
    'lastUsed'?: ProjectApiKeyLastUsed;
    /**
    * If the key has a ttl set, when the key will expire
    */
    'expires'?: Date;
    'type': ActorProjectApiKeyTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "apiKey",
            "baseName": "apiKey",
            "type": "string"
        },
        {
            "name": "isDevelopmentKey",
            "baseName": "isDevelopmentKey",
            "type": "boolean"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "ActorProjectApiKeyRoleEnum"
        },
        {
            "name": "createdByUser",
            "baseName": "createdByUser",
            "type": "CreatedUpdatedByUser"
        },
        {
            "name": "lastUsed",
            "baseName": "lastUsed",
            "type": "ProjectApiKeyLastUsed"
        },
        {
            "name": "expires",
            "baseName": "expires",
            "type": "Date"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ActorProjectApiKeyTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return ActorProjectApiKey.attributeTypeMap;
    }
}


export type ActorProjectApiKeyRoleEnum = 'admin' | 'readonly' | 'ingestiononly' | 'ingestion_deployment' | 'wladmin';
export const ActorProjectApiKeyRoleEnumValues: string[] = ['admin', 'readonly', 'ingestiononly', 'ingestion_deployment', 'wladmin'];

export type ActorProjectApiKeyTypeEnum = 'projectApiKey';
export const ActorProjectApiKeyTypeEnumValues: string[] = ['projectApiKey'];
