/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreatedUpdatedByUser } from './createdUpdatedByUser';

export class ActorOAuthClient {
    'type': ActorOAuthClientTypeEnum;
    'id': number;
    'clientId': string;
    'name': string;
    'logoUrl'?: string;
    'user'?: CreatedUpdatedByUser;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ActorOAuthClientTypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "clientId",
            "baseName": "clientId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "logoUrl",
            "baseName": "logoUrl",
            "type": "string"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "CreatedUpdatedByUser"
        }    ];

    static getAttributeTypeMap() {
        return ActorOAuthClient.attributeTypeMap;
    }
}


export type ActorOAuthClientTypeEnum = 'oauthClient';
export const ActorOAuthClientTypeEnumValues: string[] = ['oauthClient'];
