// Generated by studio/openapi/generate-models/convert.ts

import type { ExtensionVisibility } from './models';
import type { ProjectApiKeyRole } from './models';
import type { PublicProjectTierAvailability } from './models';

export type AddOrganizationExtensionBlockRequest = {
    /**
    * Extension block name.
    */
    name: string;
    /**
    * Required if "visibility" is "project". If set, this extension is scoped to this specific project.
    */
    onlyAvailableInProjectId?: number | null;
    /**
    * Extension block description.
    */
    description: string;
    /**
    * URL loaded by the extension.
    */
    url: string;
    /**
    * Optional source repository URL for the extension.
    */
    repositoryUrl?: string;
    /**
    * Optional logo image for the extension.
    */
    logo?: { fieldname: string, originalname: string, encoding: string, mimetype: string, buffer: Buffer, size: number }[];
    /**
    * Optional Font Awesome icon class for the navigation item.
    */
    navbarIcon?: string;
    /**
    * Studio navigation location for the extension.
    */
    navbarLocation: AddOrganizationExtensionBlockRequestNavbarLocationEnum;
    requiredApiKeyRole: ProjectApiKeyRole;
    visibility?: ExtensionVisibility;
    publicProjectTierAvailability?: PublicProjectTierAvailability;
    /**
    * Whether this extension is no longer available.
    */
    indBlockNoLongerAvailable?: boolean;
    /**
    * Reason this extension is no longer available.
    */
    blockNoLongerAvailableReason?: string;
};

export type AddOrganizationExtensionBlockRequestNavbarLocationEnum = 'project' | 'devices' | 'data_acquisition' | 'experiments' | 'create_impulse' | 'dsp_block' | 'learn_block' | 'live_classification' | 'model_testing' | 'deployment' | 'impulse' | 'versioning';
export const AddOrganizationExtensionBlockRequestNavbarLocationEnumValues: string[] = [ 'project', 'devices', 'data_acquisition', 'experiments', 'create_impulse', 'dsp_block', 'learn_block', 'live_classification', 'model_testing', 'deployment', 'impulse', 'versioning' ];
