// Generated by studio/openapi/generate-models/convert.ts

import type { ProjectTierEnum } from './projectTierEnum';
import type { ProjectType } from './projectType';

export type AdminApiProject = {
    id: number;
    name: string;
    description?: string;
    created?: Date;
    /**
    * User or organization that owns the project
    */
    owner: string;
    ownerUserId?: number;
    ownerOrganizationId?: number;
    lastAccessed?: Date;
    /**
    * Unique identifier of the white label this project belongs to, if any.
    */
    whitelabelId?: number | null;
    tier?: ProjectTierEnum;
    category?: ProjectType;
    deletedDate?: Date;
};
