/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BoundingBoxWithScore } from './boundingBoxWithScore';

export class AnomalyResult {
    /**
    * For visual anomaly detection. An array of bounding box objects, (x, y, width, height, score, label), one per detection in the image. Filtered by the minimum confidence rating of the learn block.
    */
    'boxes'?: Array<BoundingBoxWithScore>;
    /**
    * 2D array of shape (n, n) with raw anomaly scores for visual anomaly detection, where n can be calculated as ((1/8 of image input size)/2 - 1). The scores corresponds to each grid cell in the image\'s spatial matrix.
    */
    'scores'?: Array<Array<number>>;
    /**
    * Mean value of the scores.
    */
    'meanScore'?: number;
    /**
    * Maximum value of the scores.
    */
    'maxScore'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "boxes",
            "baseName": "boxes",
            "type": "Array<BoundingBoxWithScore>"
        },
        {
            "name": "scores",
            "baseName": "scores",
            "type": "Array<Array<number>>"
        },
        {
            "name": "meanScore",
            "baseName": "meanScore",
            "type": "number"
        },
        {
            "name": "maxScore",
            "baseName": "maxScore",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AnomalyResult.attributeTypeMap;
    }
}

