// Generated by studio/openapi/generate-models/convert.ts

import type { AnomalyConfigAxes } from './anomalyConfigAxes';
import type { BlockThreshold } from './blockThreshold';
import type { DependencyData } from './dependencyData';

export type AnomalyConfigResponse = {
    /**
    * Whether the operation succeeded
    */
    success: boolean;
    /**
    * Optional error description (set if 'success' was false)
    */
    error?: string;
    dependencies: DependencyData;
    name: string;
    /**
    * Selectable axes for the anomaly detection block
    */
    axes: AnomalyConfigAxes[];
    /**
    * Whether the block is trained
    */
    trained: boolean;
    /**
    * Number of clusters for K-means, or number of components for GMM (in config)
    */
    clusterCount?: number;
    /**
    * Selected clusters (in config)
    */
    selectedAxes: number[];
    /**
    * DEPRECATED, see "thresholds" instead. Minimum confidence rating for this block, scores above this number will be
    * flagged as anomaly.
    */
    minimumConfidenceRating: number;
    /**
    * List of configurable thresholds for this block.
    */
    thresholds: BlockThreshold[];
};
