// Generated by studio/openapi/generate-models/convert.ts

export type AugmentationPolicySpectrogram = {
    /**
    * True if spectrogram augmentation is enabled. Other properties will be ignored if this is false.
    */
    enabled: boolean;
    /**
    * True if warping along the time axis is enabled.
    */
    warping?: boolean;
    /**
    * The amount of frequency masking to apply.
    */
    freqMasking?: AugmentationPolicySpectrogramFreqMaskingEnum;
    /**
    * The amount of time masking to apply.
    */
    timeMasking?: AugmentationPolicySpectrogramTimeMaskingEnum;
    /**
    * The amount of Gaussian noise to add.
    */
    gaussianNoise?: AugmentationPolicySpectrogramGaussianNoiseEnum;
};

export type AugmentationPolicySpectrogramFreqMaskingEnum = 'none' | 'low' | 'high';
export const AugmentationPolicySpectrogramFreqMaskingEnumValues: string[] = [ 'none', 'low', 'high' ];

export type AugmentationPolicySpectrogramTimeMaskingEnum = 'none' | 'low' | 'high';
export const AugmentationPolicySpectrogramTimeMaskingEnumValues: string[] = [ 'none', 'low', 'high' ];

export type AugmentationPolicySpectrogramGaussianNoiseEnum = 'none' | 'low' | 'high';
export const AugmentationPolicySpectrogramGaussianNoiseEnumValues: string[] = [ 'none', 'low', 'high' ];
