/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class BackToLabelingRequest {
    /**
    * Defines what should happen to labels during the action. Use \"clear-labels\" to remove all existing labels.
    */
    'labelAction': BackToLabelingRequestLabelActionEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "labelAction",
            "baseName": "labelAction",
            "type": "BackToLabelingRequestLabelActionEnum"
        }    ];

    static getAttributeTypeMap() {
        return BackToLabelingRequest.attributeTypeMap;
    }
}


export type BackToLabelingRequestLabelActionEnum = 'clear-labels';
export const BackToLabelingRequestLabelActionEnumValues: string[] = ['clear-labels'];
