// Generated by studio/openapi/generate-models/convert.ts

export type BuildOnDeviceModelResponse = {
    /**
    * Whether the operation succeeded
    */
    success: boolean;
    /**
    * Optional error description (set if 'success' was false)
    */
    error?: string;
    /**
    * Job identifier. Status updates will include this identifier.
    */
    id: number;
    /**
    * Deployment version, use `downloadHistoricDeployment` to later download the deployment using this identifier.
    */
    deploymentVersion: number;
};
