// Generated by studio/openapi/generate-models/convert.ts

export type CanaryResponse = {
    /**
    * Whether the operation succeeded
    */
    success: boolean;
    /**
    * Optional error description (set if 'success' was false)
    */
    error?: string;
    /**
    * Whether the request should be routed to the canary or not.
    */
    routeToCanary: boolean;
};
