/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AdditionalMetric } from './additionalMetric';

export class ClassifyJobResponseAllOfAdditionalMetricsByLearnBlock {
    'learnBlockId': number;
    'learnBlockName': string;
    'additionalMetrics': Array<AdditionalMetric>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "learnBlockId",
            "baseName": "learnBlockId",
            "type": "number"
        },
        {
            "name": "learnBlockName",
            "baseName": "learnBlockName",
            "type": "string"
        },
        {
            "name": "additionalMetrics",
            "baseName": "additionalMetrics",
            "type": "Array<AdditionalMetric>"
        }    ];

    static getAttributeTypeMap() {
        return ClassifyJobResponseAllOfAdditionalMetricsByLearnBlock.attributeTypeMap;
    }
}

