/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CosineSimilarityIssueWindows } from './cosineSimilarityIssueWindows';
import { Sample } from './sample';

export class CosineSimilarityIssueIssues {
    /**
    * The ID of this sample
    */
    'id': number;
    'sample'?: Sample;
    /**
    * The label of this sample, in index form
    */
    'label': number;
    /**
    * The windows in this sample that are symptomatic of this issue.
    */
    'windows': Array<CosineSimilarityIssueWindows>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "sample",
            "baseName": "sample",
            "type": "Sample"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "number"
        },
        {
            "name": "windows",
            "baseName": "windows",
            "type": "Array<CosineSimilarityIssueWindows>"
        }    ];

    static getAttributeTypeMap() {
        return CosineSimilarityIssueIssues.attributeTypeMap;
    }
}

