// Generated by studio/openapi/generate-models/convert.ts

export type CreateThirdPartyAuthRequest = {
    name: string;
    description: string;
    logo: string;
    domains: string[];
    secretKey?: string;
    apiKey?: string;
};
