// Generated by studio/openapi/generate-models/convert.ts

export type CreateTestUserResponse = {
    /**
    * Whether the operation succeeded
    */
    success: boolean;
    /**
    * Optional error description (set if 'success' was false)
    */
    error?: string;
    /**
    * User ID of the created test user
    */
    id: number;
    email?: string;
    username?: string;
    /**
    * Generated password (only returned if not provided in request)
    */
    password?: string;
    /**
    * JWT token for immediate authentication
    */
    jwtToken?: string;
};
