/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateEnterpriseTrialResponseAllOf } from './createEnterpriseTrialResponseAllOf';
import { EntityCreatedResponse } from './entityCreatedResponse';

export class CreateEnterpriseTrialResponse {
    /**
    * Whether the operation succeeded
    */
    'success': boolean;
    /**
    * Optional error description (set if \'success\' was false)
    */
    'error'?: string;
    /**
    * Unique identifier of the created entity, if any.
    */
    'id'?: number | null;
    /**
    * ID of the user created for the trial, if the user did not already exist.
    */
    'userId'?: number;
    /**
    * URL to redirect the user to in order to access the enterprise trial.
    */
    'redirectUrl'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "number"
        },
        {
            "name": "redirectUrl",
            "baseName": "redirectUrl",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateEnterpriseTrialResponse.attributeTypeMap;
    }
}

