// Generated by studio/openapi/generate-models/convert.ts

export type DatasetVersionPendingWindow = {
    /**
    * Temporary window ID that cannot be used for retrieval. The window is deleted after a successful commit.
    */
    windowId: number;
    /**
    * Date and time when this dataset version window opened.
    */
    windowStart: Date;
    /**
    * Date and time when this dataset version window closed.
    */
    windowEnd: Date | null;
};
