// Generated by studio/openapi/generate-models/convert.ts

export type DatasetSplitOptions = {
    /**
    * Proportion of the dataset to use for training.
    */
    trainingSplitRatio: number;
    /**
    * Proportion of the dataset to use for testing.
    */
    testingSplitRatio: number;
    /**
    * Proportion of the dataset to use for validation. This is experimental and may change in the future.
    */
    validationSplitRatio?: number;
    /**
    * Whether to exclude samples that are marked as disabled.
    */
    excludeDisabledSamples?: boolean;
    /**
    * Optional balancing targets for the split.
    */
    stratifyBy?: {
        /**
        * Whether to stratify by label.
        */
        label?: boolean;
        /**
        * Metadata keys to use as balancing targets. If more than one is selected, they are combined into composite
        * assignment buckets.
        */
        metadataKeys?: string[];
    };
    /**
    * List of metadata keys whose matching values must stay together in a single split. This is useful for leakage
    * prevention across train, validation, and test.
    */
    keepTogetherMetadataKeys?: string[];
};
