/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class DataCampaignDashboard {
    'id': number;
    'created': Date;
    'name': string;
    /**
    * List of user IDs to notify for this dashboard (sent daily)
    */
    'emailRecipientUids': Array<number>;
    'latestScreenshot'?: string;
    'whenToEmail': DataCampaignDashboardWhenToEmailEnum;
    'showNoOfDays': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "emailRecipientUids",
            "baseName": "emailRecipientUids",
            "type": "Array<number>"
        },
        {
            "name": "latestScreenshot",
            "baseName": "latestScreenshot",
            "type": "string"
        },
        {
            "name": "whenToEmail",
            "baseName": "whenToEmail",
            "type": "DataCampaignDashboardWhenToEmailEnum"
        },
        {
            "name": "showNoOfDays",
            "baseName": "showNoOfDays",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return DataCampaignDashboard.attributeTypeMap;
    }
}


export type DataCampaignDashboardWhenToEmailEnum = 'always' | 'on_changes' | 'never';
export const DataCampaignDashboardWhenToEmailEnumValues: string[] = ['always', 'on_changes', 'never'];
