// Generated by studio/openapi/generate-models/convert.ts

import type { ObjectDetectionLastLayer } from './objectDetectionLastLayer';

export type DeployPretrainedModelModelObjectDetection = {
    modelType: DeployPretrainedModelModelObjectDetectionModelTypeEnum;
    labels: string[];
    lastLayer: ObjectDetectionLastLayer;
    /**
    * Deprecated: use thresholdValues instead. Threshold for objects (f.e. 0.3).
    */
    minimumConfidence: number;
    /**
    * All configured thresholds for the current model. Valid keys are 'min_score' (object detection models, all but
    * paddleocr-detector); 'min_score_pixel', 'min_score_box', 'unclip_ratio' (paddleocr-detector).
    */
    thresholdValues?: { [key: string]: number; };
};

export type DeployPretrainedModelModelObjectDetectionModelTypeEnum = 'object-detection';
export const DeployPretrainedModelModelObjectDetectionModelTypeEnumValues: string[] = [ 'object-detection' ];
