// Generated by studio/openapi/generate-models/convert.ts

export type DeployPretrainedModelInputTimeSeries = {
    inputType: DeployPretrainedModelInputTimeSeriesInputTypeEnum;
    frequencyHz: number;
    windowLengthMs: number;
};

export type DeployPretrainedModelInputTimeSeriesInputTypeEnum = 'time-series';
export const DeployPretrainedModelInputTimeSeriesInputTypeEnumValues: string[] = [ 'time-series' ];
