/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DeployPretrainedModelRequestModelInfo } from './deployPretrainedModelRequestModelInfo';
import { DeploymentTargetEngine } from './deploymentTargetEngine';

export class DeployPretrainedModelRequest {
    /**
    * A base64 encoded pretrained model
    */
    'modelFileBase64': string;
    'modelFileType': DeployPretrainedModelRequestModelFileTypeEnum;
    /**
    * The name of the built target. You can find this by listing all deployment targets through `listDeploymentTargetsForProject` (via `GET /v1/api/{projectId}/deployment/targets`) and see the `format` type.
    */
    'deploymentType': string;
    'engine'?: DeploymentTargetEngine;
    'modelInfo': DeployPretrainedModelRequestModelInfo;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "modelFileBase64",
            "baseName": "modelFileBase64",
            "type": "string"
        },
        {
            "name": "modelFileType",
            "baseName": "modelFileType",
            "type": "DeployPretrainedModelRequestModelFileTypeEnum"
        },
        {
            "name": "deploymentType",
            "baseName": "deploymentType",
            "type": "string"
        },
        {
            "name": "engine",
            "baseName": "engine",
            "type": "DeploymentTargetEngine"
        },
        {
            "name": "modelInfo",
            "baseName": "modelInfo",
            "type": "DeployPretrainedModelRequestModelInfo"
        }    ];

    static getAttributeTypeMap() {
        return DeployPretrainedModelRequest.attributeTypeMap;
    }
}


export type DeployPretrainedModelRequestModelFileTypeEnum = 'tflite';
export const DeployPretrainedModelRequestModelFileTypeEnumValues: string[] = ['tflite'];
