// Generated by studio/openapi/generate-models/convert.ts

import type { DSPGroupItem } from './dSPGroupItem';
import type { DeploymentTargetBadge } from './deploymentTargetBadge';
import type { DeploymentTargetEngine } from './deploymentTargetEngine';
import type { DeploymentTargetRedirect } from './deploymentTargetRedirect';
import type { DeploymentTargetVariant } from './deploymentTargetVariant';

export type DeploymentTarget = {
    name: string;
    description: string;
    image: string;
    imageClasses: string;
    format: string;
    latencyDevice?: string;
    /**
    * Preferably use supportedEngines / preferredEngine
    */
    hasEonCompiler: boolean;
    /**
    * Preferably use supportedEngines / preferredEngine
    */
    hasTensorRT: boolean;
    /**
    * Preferably use supportedEngines / preferredEngine
    */
    hasTensaiFlow: boolean;
    /**
    * Preferably use supportedEngines / preferredEngine
    */
    hasDRPAI: boolean;
    /**
    * Preferably use supportedEngines / preferredEngine
    */
    hasTIDL: boolean;
    /**
    * Preferably use supportedEngines / preferredEngine
    */
    hasAkida: boolean;
    /**
    * Preferably use supportedEngines / preferredEngine
    */
    hasMemryx: boolean;
    /**
    * Preferably use supportedEngines / preferredEngine
    */
    hasStAton: boolean;
    /**
    * Preferably use supportedEngines / preferredEngine
    */
    hasCevaNpn: boolean;
    /**
    * Preferably use supportedEngines / preferredEngine
    */
    hasNordicAxon: boolean;
    hideOptimizations: boolean;
    badge?: DeploymentTargetBadge;
    uiSection: DeploymentTargetUiSectionEnum;
    customDeployId?: number;
    customDeployOrganizationId?: number;
    integrateUrl?: string;
    ownerOrganizationName?: string;
    supportedEngines: DeploymentTargetEngine[];
    preferredEngine: DeploymentTargetEngine;
    url?: string;
    docsUrl: string;
    firmwareRepoUrl?: string;
    modelVariants: DeploymentTargetVariant[];
    parameters: DSPGroupItem[];
    /**
    * An optional redirect field for integration partners to be shown in addition to the docs link, i.e. for directing
    * users to a partner's website or application once deployment completes. This is experimental and may change in the
    * future.
    */
    redirect?: DeploymentTargetRedirect;
};

export type DeploymentTargetUiSectionEnum = 'library' | 'firmware' | 'mobile' | 'hidden';
export const DeploymentTargetUiSectionEnumValues: string[] = [ 'library', 'firmware', 'mobile', 'hidden' ];
