// Generated by studio/openapi/generate-models/convert.ts

import type { DspAutotunerResultsAllOfResults } from './dspAutotunerResultsAllOfResults';

export type DspAutotunerResults = {
    /**
    * Whether the operation succeeded
    */
    success: boolean;
    /**
    * Optional error description (set if 'success' was false)
    */
    error?: string;
    results: DspAutotunerResultsAllOfResults[];
};
