/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DSPGroupItem } from './dSPGroupItem';

export class DSPGroup {
    'group': string;
    'items': Array<DSPGroupItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "group",
            "baseName": "group",
            "type": "string"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<DSPGroupItem>"
        }    ];

    static getAttributeTypeMap() {
        return DSPGroup.attributeTypeMap;
    }
}

