/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class DSPInfoFeatures {
    /**
    * Whether this block has generated features
    */
    'generated': boolean;
    /**
    * Number of generated features
    */
    'count'?: number;
    /**
    * Names of the features
    */
    'labels'?: Array<string>;
    /**
    * Classes that the features were generated on
    */
    'classes'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "generated",
            "baseName": "generated",
            "type": "boolean"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number"
        },
        {
            "name": "labels",
            "baseName": "labels",
            "type": "Array<string>"
        },
        {
            "name": "classes",
            "baseName": "classes",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return DSPInfoFeatures.attributeTypeMap;
    }
}

