// Generated by studio/openapi/generate-models/convert.ts

export type DspRunGraph = {
    /**
    * Name of the graph
    */
    name: string;
    /**
    * Base64 encoded image, only present if type is 'image'
    */
    image?: string;
    /**
    * Mime type of the Base64 encoded image, only present if type is 'image'
    */
    imageMimeType?: string;
    /**
    * Values on the x-axis per plot. Key is the name of the raw feature. Present if type is 'logarithmic' or 'linear'.
    */
    X?: { [key: string]: number[]; };
    /**
    * Values of the y-axis. Present if type is 'logarithmic' or 'linear'.
    */
    y?: number[];
    /**
    * Suggested minimum value of x-axis
    */
    suggestedXMin?: number;
    /**
    * Suggested maxium value of x-axis
    */
    suggestedXMax?: number;
    /**
    * Suggested minimum value of y-axis
    */
    suggestedYMin?: number;
    /**
    * Suggested maximum value of y-axis
    */
    suggestedYMax?: number;
    /**
    * Type of graph (either `logarithmic`, `linear` or `image`)
    */
    type: string;
    /**
    * Width of the graph line (if type is `logarithmic` or `linear`). Default 3.
    */
    lineWidth?: number;
    /**
    * Whether to apply smoothing to the graph.
    */
    smoothing?: boolean;
    /**
    * Labels for the graph x and y axes.
    */
    axisLabels?: {
        X: string;
        y: string;
    };
    /**
    * Indices of points to highlight, per axis.
    */
    highlights?: { [key: string]: number[]; };
};
