// Generated by studio/openapi/generate-models/convert.ts

export type DspRunRequestWithoutFeaturesReadOnly = {
    /**
    * DSP parameters with values
    */
    params: { [key: string]: string | null; };
};
