// Generated by studio/openapi/generate-models/convert.ts

export type EntitlementLimits = {
    /**
    * Storage entitlement, in bytes
    */
    totalStorage?: number;
    /**
    * Total compute time entitlement (CPU + GPU), in seconds
    */
    computeTimePerYear?: number;
    /**
    * GPU compute time entitlement, in seconds
    */
    gpuComputeTimePerYear?: number;
    /**
    * Number of projects allowed for this organization
    */
    numberOfProjects?: number;
    /**
    * Number of users allowed for this organization
    */
    numberOfUsers?: number;
};
