/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AutoLabelerSegment } from './autoLabelerSegment';
import { Sample } from './sample';

export class GetAutoLabelerSegmentInfoResponseAllOf {
    'sample': Sample;
    'imageUrl': string;
    'segments': Array<AutoLabelerSegment>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sample",
            "baseName": "sample",
            "type": "Sample"
        },
        {
            "name": "imageUrl",
            "baseName": "imageUrl",
            "type": "string"
        },
        {
            "name": "segments",
            "baseName": "segments",
            "type": "Array<AutoLabelerSegment>"
        }    ];

    static getAttributeTypeMap() {
        return GetAutoLabelerSegmentInfoResponseAllOf.attributeTypeMap;
    }
}

