// Generated by studio/openapi/generate-models/convert.ts

import type { Sample } from './sample';

export type GetDatasetVersionRawDataSampleResponse = {
    /**
    * Whether the operation succeeded
    */
    success: boolean;
    /**
    * Optional error description (set if 'success' was false)
    */
    error?: string;
    sample: Sample;
};
