/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class GetJWTResponseAllOf {
    /**
    * JWT token, to be used to log in in the future through JWTAuthentication
    */
    'token'?: string;
    /**
    * Redirect URL to follow to complete login
    */
    'redirectUrl'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "token",
            "baseName": "token",
            "type": "string"
        },
        {
            "name": "redirectUrl",
            "baseName": "redirectUrl",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GetJWTResponseAllOf.attributeTypeMap;
    }
}

