// Generated by studio/openapi/generate-models/convert.ts

import type { SelfServeOAuthClient } from './selfServeOAuthClient';

export type GetOrganizationOAuthClientResponse = {
    /**
    * Whether the operation succeeded
    */
    success: boolean;
    /**
    * Optional error description (set if 'success' was false)
    */
    error?: string;
    oauthClient: SelfServeOAuthClient;
};
