/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GetPostProcessingResultsForSampleResponseAllOfJobIsRunning } from './getPostProcessingResultsForSampleResponseAllOfJobIsRunning';
import { GetPostProcessingResultsForSampleResponseAllOfResults } from './getPostProcessingResultsForSampleResponseAllOfResults';

export class GetPostProcessingResultsForSampleResponseAllOf {
    'hasResults': GetPostProcessingResultsForSampleResponseAllOfHasResultsEnum;
    'results'?: GetPostProcessingResultsForSampleResponseAllOfResults;
    'jobIsRunning'?: GetPostProcessingResultsForSampleResponseAllOfJobIsRunning;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "hasResults",
            "baseName": "hasResults",
            "type": "GetPostProcessingResultsForSampleResponseAllOfHasResultsEnum"
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "GetPostProcessingResultsForSampleResponseAllOfResults"
        },
        {
            "name": "jobIsRunning",
            "baseName": "jobIsRunning",
            "type": "GetPostProcessingResultsForSampleResponseAllOfJobIsRunning"
        }    ];

    static getAttributeTypeMap() {
        return GetPostProcessingResultsForSampleResponseAllOf.attributeTypeMap;
    }
}


export type GetPostProcessingResultsForSampleResponseAllOfHasResultsEnum = 'has-results' | 'job-is-running' | 'no-results';
export const GetPostProcessingResultsForSampleResponseAllOfHasResultsEnumValues: string[] = ['has-results', 'job-is-running', 'no-results'];
