// Generated by studio/openapi/generate-models/convert.ts

import type { PerformanceCalibrationGroundTruth } from './performanceCalibrationGroundTruth';

export type GetPerformanceCalibrationGroundTruthResponse = {
    /**
    * Whether the operation succeeded
    */
    success: boolean;
    /**
    * Optional error description (set if 'success' was false)
    */
    error?: string;
    samples: PerformanceCalibrationGroundTruth[];
};
