/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MetadataDistributionBucket } from './metadataDistributionBucket';
import { MetadataDistributionLabelBreakdown } from './metadataDistributionLabelBreakdown';
import { RawDataCategory } from './rawDataCategory';

export class GetRawDataMetadataDistributionResponseAllOf {
    'key': string;
    'category': RawDataCategory;
    'sampleCount': number;
    'totalCount': number;
    'missingCount': number;
    'coveragePct': number;
    'uniqueValueCount': number;
    'type': GetRawDataMetadataDistributionResponseAllOfTypeEnum;
    'buckets': Array<MetadataDistributionBucket>;
    'labelBreakdown'?: Array<MetadataDistributionLabelBreakdown>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "RawDataCategory"
        },
        {
            "name": "sampleCount",
            "baseName": "sampleCount",
            "type": "number"
        },
        {
            "name": "totalCount",
            "baseName": "totalCount",
            "type": "number"
        },
        {
            "name": "missingCount",
            "baseName": "missingCount",
            "type": "number"
        },
        {
            "name": "coveragePct",
            "baseName": "coveragePct",
            "type": "number"
        },
        {
            "name": "uniqueValueCount",
            "baseName": "uniqueValueCount",
            "type": "number"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "GetRawDataMetadataDistributionResponseAllOfTypeEnum"
        },
        {
            "name": "buckets",
            "baseName": "buckets",
            "type": "Array<MetadataDistributionBucket>"
        },
        {
            "name": "labelBreakdown",
            "baseName": "labelBreakdown",
            "type": "Array<MetadataDistributionLabelBreakdown>"
        }    ];

    static getAttributeTypeMap() {
        return GetRawDataMetadataDistributionResponseAllOf.attributeTypeMap;
    }
}


export type GetRawDataMetadataDistributionResponseAllOfTypeEnum = 'categorical' | 'numeric';
export const GetRawDataMetadataDistributionResponseAllOfTypeEnumValues: string[] = ['categorical', 'numeric'];
