/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JobState } from './jobState';

export class JobDetailsAllOf {
    /**
    * List of jobs children isd triggered by this job
    */
    'childrenIds'?: Array<number>;
    /**
    * List of states the job went through
    */
    'states': Array<JobState>;
    /**
    * Job specification (Kubernetes specification or other underlying engine)
    */
    'spec'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "childrenIds",
            "baseName": "childrenIds",
            "type": "Array<number>"
        },
        {
            "name": "states",
            "baseName": "states",
            "type": "Array<JobState>"
        },
        {
            "name": "spec",
            "baseName": "spec",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return JobDetailsAllOf.attributeTypeMap;
    }
}

