// Generated by studio/openapi/generate-models/convert.ts

export type JobLogItem = {
    created: Date;
    data: string;
    logLevel?: JobLogItemLogLevelEnum;
};

export type JobLogItemLogLevelEnum = 'error' | 'warn' | 'info' | 'debug';
export const JobLogItemLogLevelEnumValues: string[] = [ 'error', 'warn', 'info', 'debug' ];
