// Generated by studio/openapi/generate-models/convert.ts

export type KerasModelTypeEnum = 'int8' | 'float32' | 'akida' | 'requiresRetrain';
export const KerasModelTypeEnumValues: string[] = [ 'int8', 'float32', 'akida', 'requiresRetrain' ];
