/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ListPortalFilesInFolderRequest {
    /**
    * S3 prefix
    */
    'prefix': string;
    /**
    * If set, then only fetch folders - no files
    */
    'onlyFetchFolders'?: boolean;
    /**
    * Only one S3 page (1000 items typically) is returned. Pass in the continuationToken on the next request to receive the next page.
    */
    'continuationToken'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "prefix",
            "baseName": "prefix",
            "type": "string"
        },
        {
            "name": "onlyFetchFolders",
            "baseName": "onlyFetchFolders",
            "type": "boolean"
        },
        {
            "name": "continuationToken",
            "baseName": "continuationToken",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ListPortalFilesInFolderRequest.attributeTypeMap;
    }
}

