// Generated by studio/openapi/generate-models/convert.ts

import type { ProjectHmacKey } from './projectHmacKey';

export type ListHmacKeysResponse = {
    /**
    * Whether the operation succeeded
    */
    success: boolean;
    /**
    * Optional error description (set if 'success' was false)
    */
    error?: string;
    /**
    * List of HMAC keys
    */
    hmacKeys: ProjectHmacKey[];
};
