// Generated by studio/openapi/generate-models/convert.ts

import type { OrganizationDataItem } from './organizationDataItem';

export type ListOrganizationFilesResponse = {
    /**
    * Whether the operation succeeded
    */
    success: boolean;
    /**
    * Optional error description (set if 'success' was false)
    */
    error?: string;
    filterParseError?: string;
    totalFileSize: number;
    totalFileCount: number;
    totalDataItemCount: number;
    data: OrganizationDataItem[];
};
