// Generated by studio/openapi/generate-models/convert.ts

export type ListOrganizationBucketsUserResponse = {
    /**
    * Whether the operation succeeded
    */
    success: boolean;
    /**
    * Optional error description (set if 'success' was false)
    */
    error?: string;
    buckets: {
        id: number;
        organizationId: number;
        organizationName: string;
        /**
        * S3 bucket
        */
        bucket: string;
        /**
        * S3 region
        */
        region: string;
        /**
        * The unique identifier of the white label this bucket belongs to, if any
        */
        whitelabelId: number;
    }[];
};
