// Generated by studio/openapi/generate-models/convert.ts

import type { Project } from './project';

export type ListProjectsResponse = {
    /**
    * Whether the operation succeeded
    */
    success: boolean;
    /**
    * Optional error description (set if 'success' was false)
    */
    error?: string;
    /**
    * Array with projects
    */
    projects: Project[];
};
