// Generated by studio/openapi/generate-models/convert.ts

export type ObjectDetectionAutoLabelRequest = {
    neuralNetwork: ObjectDetectionAutoLabelRequestNeuralNetworkEnum;
};

export type ObjectDetectionAutoLabelRequestNeuralNetworkEnum = 'yolov5' | 'yolo-pro' | 'currentProject';
export const ObjectDetectionAutoLabelRequestNeuralNetworkEnumValues: string[] = [ 'yolov5', 'yolo-pro', 'currentProject' ];
