// Generated by studio/openapi/generate-models/convert.ts

export type OptimizeConfigOptimizationObjectives = {
    /**
    * Objective to optimize
    */
    objective: string;
    /**
    * Label of the objective
    */
    label: string;
    /**
    * Weight of the objective
    */
    weight: number;
};
