// Generated by studio/openapi/generate-models/convert.ts

/**
* Search space source
*/
export type OptimizeConfigSearchSpaceSource = {
    /**
    * Search space source type
    */
    type: OptimizeConfigSearchSpaceSourceTypeEnum;
    /**
    * Search space source template title
    */
    templateTitle?: string;
    /**
    * Search space source run title
    */
    runTitle?: string;
    /**
    * Search space source impulse title
    */
    impulseTitle?: string;
};

export type OptimizeConfigSearchSpaceSourceTypeEnum = 'template' | 'run' | 'impulse' | 'custom';
export const OptimizeConfigSearchSpaceSourceTypeEnumValues: string[] = [ 'template', 'run', 'impulse', 'custom' ];
