// Generated by studio/openapi/generate-models/convert.ts

import type { OptimizeConfig } from './optimizeConfig';
import type { TunerTrial } from './tunerTrial';

export type OptimizeStateResponse = {
    /**
    * Whether the operation succeeded
    */
    success: boolean;
    /**
    * Optional error description (set if 'success' was false)
    */
    error?: string;
    config: OptimizeConfig;
    status: {
        numPendingTrials: number;
        numRunningTrials: number;
        numCompletedTrials: number;
        numFailedTrials: number;
        numReadyWorkers: number;
        numBusyWorkers: number;
        numPendingWorkers: number;
        status: OptimizeStateResponseAllOfStatusStatusEnum;
    };
    /**
    * Actual tuner process, job message events will be tagged with this ID
    */
    tunerJobId?: number;
    /**
    * The coordinator pod, attach the job runner to this process for finished events
    */
    tunerCoordinatorJobId?: number;
    /**
    * Job ID for the initial job this job continuous the hyperparameter search process for.
    */
    continuationJobId?: number;
    /**
    * Tuning algorithm to use to search hyperparameter space
    */
    tuningAlgorithm?: OptimizeStateResponseTuningAlgorithmEnum;
    /**
    * Whether the job is active (if false => finished)
    */
    tunerJobIsRunning: boolean;
    trials: TunerTrial[];
    projectDataType: OptimizeStateResponseProjectDataTypeEnum;
    jobError?: string;
    workers: {
        workerId: string;
        status: OptimizeStateResponseAllOfWorkersStatusEnum;
    }[];
    /**
    * Index of the next run to be created. Used to pre-populate the name of the next run.
    */
    nextRunIndex: number;
    /**
    * Whether the search can be extended to evaluate more candidate models. Extending is possible if the search space
    * contains candidate models that are expected to perform better than the current best candidate. And extending is
    * also possible if the previous run was paused due to the total runtime limit being exceeded.
    */
    canExtendSearch: boolean;
    isWhitelabel: boolean;
    /**
    * Whether the total training time has exceeded the defined limit for the current run.
    */
    totalTrainingTimeExceeded: boolean;
};

export type OptimizeStateResponseAllOfStatusStatusEnum = 'creating' | 'ready' | 'running' | 'completed';
export const OptimizeStateResponseAllOfStatusStatusEnumValues: string[] = [ 'creating', 'ready', 'running', 'completed' ];

export type OptimizeStateResponseTuningAlgorithmEnum = 'random' | 'hyperband' | 'bayesian' | 'custom';
export const OptimizeStateResponseTuningAlgorithmEnumValues: string[] = [ 'random', 'hyperband', 'bayesian', 'custom' ];

export type OptimizeStateResponseProjectDataTypeEnum = 'audio' | 'image' | 'motion' | 'other';
export const OptimizeStateResponseProjectDataTypeEnumValues: string[] = [ 'audio', 'image', 'motion', 'other' ];

export type OptimizeStateResponseAllOfWorkersStatusEnum = 'pending' | 'ready' | 'busy';
export const OptimizeStateResponseAllOfWorkersStatusEnumValues: string[] = [ 'pending', 'ready', 'busy' ];
