// Generated by studio/openapi/generate-models/convert.ts

import type { CreatedUpdatedByUser } from './createdUpdatedByUser';
import type { ProjectApiKeyLastUsed } from './projectApiKeyLastUsed';

export type OrganizationApiKey = {
    id: number;
    apiKey: string;
    name: string;
    created: Date;
    role: OrganizationApiKeyRoleEnum;
    isTransformationJobKey: boolean;
    createdByUser?: CreatedUpdatedByUser;
    /**
    * When this API key was last used.
    */
    lastUsed?: ProjectApiKeyLastUsed;
    /**
    * If the key has a ttl set, when the key will expire
    */
    expires?: Date;
};

export type OrganizationApiKeyRoleEnum = 'admin' | 'member';
export const OrganizationApiKeyRoleEnumValues: string[] = [ 'admin', 'member' ];
