// Generated by studio/openapi/generate-models/convert.ts

/**
* Defines the folder structure for writing to the output dataset. Used only when uploading into a default (non-clinical)
* dataset.
*/

export type OrganizationCreateProjectOutputDatasetPathRule = 'no-subfolders' | 'subfolder-per-item' | 'use-full-path';
export const OrganizationCreateProjectOutputDatasetPathRuleValues: string[] = [ 'no-subfolders', 'subfolder-per-item', 'use-full-path' ];
