// Generated by studio/openapi/generate-models/convert.ts

export type OrganizationPipelineItemCount = {
    itemCount: number;
    itemCountChecklistOK: number;
    itemCountChecklistFailed: number;
};
