/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JobCreatedByUser } from './jobCreatedByUser';

export class OrganizationDataExport {
    'id': number;
    'created': Date;
    'createdByUser'?: JobCreatedByUser;
    'jobId': number;
    'jobFinished': boolean;
    'jobFinishedSuccessful': boolean;
    /**
    * Description of the data export
    */
    'description'?: string;
    /**
    * Date when the export will expire. Default is 30 days. Maximum expiration date is 60 days from the creation date.
    */
    'expirationDate': Date;
    'downloadUrl'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "createdByUser",
            "baseName": "createdByUser",
            "type": "JobCreatedByUser"
        },
        {
            "name": "jobId",
            "baseName": "jobId",
            "type": "number"
        },
        {
            "name": "jobFinished",
            "baseName": "jobFinished",
            "type": "boolean"
        },
        {
            "name": "jobFinishedSuccessful",
            "baseName": "jobFinishedSuccessful",
            "type": "boolean"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "expirationDate",
            "baseName": "expirationDate",
            "type": "Date"
        },
        {
            "name": "downloadUrl",
            "baseName": "downloadUrl",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return OrganizationDataExport.attributeTypeMap;
    }
}

