// Generated by studio/openapi/generate-models/convert.ts

export type PerformanceCalibrationGroundTruth = {
    /**
    * Whether this region is a single sample, a region of background noise, or a region of background noise that
    * contains samples.
    */
    type: PerformanceCalibrationGroundTruthTypeEnum;
    /**
    * Index of the label in the array of all labels
    */
    labelIdx: number;
    /**
    * String label of the sample
    */
    labelString: string;
    /**
    * The start time of the region in milliseconds
    */
    start: number;
    /**
    * The length of the region in milliseconds
    */
    length: number;
    /**
    * If the region contains samples, all the samples within this region
    */
    samples?: {
        /**
        * The ID of the samples in Studio
        */
        id: number;
        /**
        * The start time of the sample in milliseconds
        */
        start: number;
        /**
        * The length of the sample in milliseconds
        */
        length: number;
        /**
        * For debugging. The index of the sample in the original Y array.
        */
        idx: number;
    }[];
};

export type PerformanceCalibrationGroundTruthTypeEnum = 'sample' | 'noise' | 'combined_noise';
export const PerformanceCalibrationGroundTruthTypeEnumValues: string[] = [ 'sample', 'noise', 'combined_noise' ];
