// Generated by studio/openapi/generate-models/convert.ts

export type PerformanceCalibrationRawDetection = {
    /**
    * The start time of the detected window in milliseconds
    */
    start: number;
    /**
    * The end time of the detected window in milliseconds
    */
    end: number;
    result: number[];
};
