/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* The project tier. This is \"enterprise\" for all organization projects, or the user tier for all user projects.
*/

export type ProjectTierEnum = 'free' | 'community-plus' | 'professional' | 'enterprise';
export const ProjectTierEnumValues: string[] = ['free', 'community-plus', 'professional', 'enterprise'];
