/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProjectCollaborator } from './projectCollaborator';

export class Project {
    'id': number;
    'name': string;
    'description': string;
    'created': Date;
    /**
    * User or organization that owns the project
    */
    'owner': string;
    'lastAccessed'?: Date;
    /**
    * Custom logo for this project (not available for all projects)
    */
    'logo'?: string;
    'ownerUserId'?: number;
    'ownerOrganizationId'?: number;
    'collaborators': Array<ProjectCollaborator>;
    'labelingMethod': ProjectLabelingMethodEnum;
    /**
    * Metadata about the project
    */
    'metadata': object;
    'dataExplorerScreenshot'?: string;
    /**
    * Whether this is an enterprise project
    */
    'isEnterpriseProject': boolean;
    /**
    * Unique identifier of the white label this project belongs to, if any.
    */
    'whitelabelId': number | null;
    /**
    * List of project tags
    */
    'tags'?: Array<string>;
    /**
    * Project category
    */
    'category'?: string;
    /**
    * Public project license, if any.
    */
    'license'?: string;
    'tier': ProjectTierEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "string"
        },
        {
            "name": "lastAccessed",
            "baseName": "lastAccessed",
            "type": "Date"
        },
        {
            "name": "logo",
            "baseName": "logo",
            "type": "string"
        },
        {
            "name": "ownerUserId",
            "baseName": "ownerUserId",
            "type": "number"
        },
        {
            "name": "ownerOrganizationId",
            "baseName": "ownerOrganizationId",
            "type": "number"
        },
        {
            "name": "collaborators",
            "baseName": "collaborators",
            "type": "Array<ProjectCollaborator>"
        },
        {
            "name": "labelingMethod",
            "baseName": "labelingMethod",
            "type": "ProjectLabelingMethodEnum"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "object"
        },
        {
            "name": "dataExplorerScreenshot",
            "baseName": "dataExplorerScreenshot",
            "type": "string"
        },
        {
            "name": "isEnterpriseProject",
            "baseName": "isEnterpriseProject",
            "type": "boolean"
        },
        {
            "name": "whitelabelId",
            "baseName": "whitelabelId",
            "type": "number"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<string>"
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "string"
        },
        {
            "name": "license",
            "baseName": "license",
            "type": "string"
        },
        {
            "name": "tier",
            "baseName": "tier",
            "type": "ProjectTierEnum"
        }    ];

    static getAttributeTypeMap() {
        return Project.attributeTypeMap;
    }
}


export type ProjectLabelingMethodEnum = 'single_label' | 'object_detection';
export const ProjectLabelingMethodEnumValues: string[] = ['single_label', 'object_detection'];

export type ProjectTierEnum = 'free' | 'pro' | 'enterprise';
export const ProjectTierEnumValues: string[] = ['free', 'pro', 'enterprise'];
