// Generated by studio/openapi/generate-models/convert.ts

import type { KerasModelVariantEnum } from './kerasModelVariantEnum';

export type ProjectModelVariant = {
    variant: KerasModelVariantEnum;
    /**
    * True if this model variant is the default or "reference variant" for this project
    */
    isReferenceVariant: boolean;
    /**
    * True if profiling for this model variant is enabled for the current project
    */
    isEnabled: boolean;
    /**
    * True if this is the selected model variant for this project, used to keep the same view after refreshing. Update
    * this via defaultProfilingVariant in UpdateProjectRequest.
    */
    isSelected: boolean;
};
