// Generated by studio/openapi/generate-models/convert.ts

/**
* Per-dataset data count
*/
export type ProjectDatasetMetadataRatioCount = {
    training: number;
    testing: number;
    validation: number;
};
