// Generated by studio/openapi/generate-models/convert.ts

/**
* When this API key was last used.
*/
export type ProjectApiKeyLastUsed = {
    date: Date;
    /**
    * If available, the country from which the API key was last used.
    */
    country?: string;
    /**
    * If available, the IP address from which the API key was last used.
    */
    ipAddress?: string;
};
