/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RawDataLabelDistributionRegressionValueGroup } from './rawDataLabelDistributionRegressionValueGroup';
import { RawDataLabelDistributionRegressionValueGroupsPerKey } from './rawDataLabelDistributionRegressionValueGroupsPerKey';

export class ProjectDatasetMetadataRegressionCategoryAllOf {
    'type': ProjectDatasetMetadataRegressionCategoryAllOfTypeEnum;
    'labelsCount': number;
    'minLabel': number;
    'maxLabel': number;
    'valueGroups': Array<RawDataLabelDistributionRegressionValueGroup>;
    'groupsPerLabelMapKey'?: { [key: string]: RawDataLabelDistributionRegressionValueGroupsPerKey; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ProjectDatasetMetadataRegressionCategoryAllOfTypeEnum"
        },
        {
            "name": "labelsCount",
            "baseName": "labelsCount",
            "type": "number"
        },
        {
            "name": "minLabel",
            "baseName": "minLabel",
            "type": "number"
        },
        {
            "name": "maxLabel",
            "baseName": "maxLabel",
            "type": "number"
        },
        {
            "name": "valueGroups",
            "baseName": "valueGroups",
            "type": "Array<RawDataLabelDistributionRegressionValueGroup>"
        },
        {
            "name": "groupsPerLabelMapKey",
            "baseName": "groupsPerLabelMapKey",
            "type": "{ [key: string]: RawDataLabelDistributionRegressionValueGroupsPerKey; }"
        }    ];

    static getAttributeTypeMap() {
        return ProjectDatasetMetadataRegressionCategoryAllOf.attributeTypeMap;
    }
}


export type ProjectDatasetMetadataRegressionCategoryAllOfTypeEnum = 'regression';
export const ProjectDatasetMetadataRegressionCategoryAllOfTypeEnumValues: string[] = ['regression'];
