/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ProjectInfoResponseAllOfUrls {
    /**
    * Base URL for the mobile client. If this is undefined then no development API key is set.
    */
    'mobileClient'?: string;
    /**
    * Base URL for collecting data with the mobile client from a computer. If this is undefined then no development API key is set.
    */
    'mobileClientComputer'?: string;
    /**
    * Base URL for running inference with the mobile client. If this is undefined then no development API key is set.
    */
    'mobileClientInference'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mobileClient",
            "baseName": "mobileClient",
            "type": "string"
        },
        {
            "name": "mobileClientComputer",
            "baseName": "mobileClientComputer",
            "type": "string"
        },
        {
            "name": "mobileClientInference",
            "baseName": "mobileClientInference",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ProjectInfoResponseAllOfUrls.attributeTypeMap;
    }
}

