/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProjectDatasetMetadataRatioCount } from './projectDatasetMetadataRatioCount';

/**
* Placeholder dataset ratio info when no ratio is available
*/
export class ProjectDatasetMetadataRatioNoRatio {
    'type': ProjectDatasetMetadataRatioNoRatioTypeEnum;
    'hasValidationCategory': boolean;
    'count': ProjectDatasetMetadataRatioCount;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ProjectDatasetMetadataRatioNoRatioTypeEnum"
        },
        {
            "name": "hasValidationCategory",
            "baseName": "hasValidationCategory",
            "type": "boolean"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "ProjectDatasetMetadataRatioCount"
        }    ];

    static getAttributeTypeMap() {
        return ProjectDatasetMetadataRatioNoRatio.attributeTypeMap;
    }
}


export type ProjectDatasetMetadataRatioNoRatioTypeEnum = 'no-ratio';
export const ProjectDatasetMetadataRatioNoRatioTypeEnumValues: string[] = ['no-ratio'];
