/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MetadataFilterOptions } from './metadataFilterOptions';
import { ProjectDatasetMetadataBase } from './projectDatasetMetadataBase';
import { ProjectDatasetMetadataRegressionCategoryAllOf } from './projectDatasetMetadataRegressionCategoryAllOf';
import { RawDataLabelDistributionRegressionValueGroup } from './rawDataLabelDistributionRegressionValueGroup';
import { RawDataLabelDistributionRegressionValueGroupsPerKey } from './rawDataLabelDistributionRegressionValueGroupsPerKey';

export class ProjectDatasetMetadataRegressionCategory {
    'type': ProjectDatasetMetadataRegressionCategoryTypeEnum;
    'totalLength': string;
    'totalLengthNumber': number;
    'maxLengthMs': number;
    'minLengthMs': number;
    'minFrequency': number;
    'maxFrequency': number;
    'itemCount': number;
    'isTimeseries': boolean;
    'isFeatures': boolean;
    'metadataFilterOptions': MetadataFilterOptions;
    'labelsCount': number;
    'minLabel': number;
    'maxLabel': number;
    'valueGroups': Array<RawDataLabelDistributionRegressionValueGroup>;
    'groupsPerLabelMapKey'?: { [key: string]: RawDataLabelDistributionRegressionValueGroupsPerKey; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ProjectDatasetMetadataRegressionCategoryTypeEnum"
        },
        {
            "name": "totalLength",
            "baseName": "totalLength",
            "type": "string"
        },
        {
            "name": "totalLengthNumber",
            "baseName": "totalLengthNumber",
            "type": "number"
        },
        {
            "name": "maxLengthMs",
            "baseName": "maxLengthMs",
            "type": "number"
        },
        {
            "name": "minLengthMs",
            "baseName": "minLengthMs",
            "type": "number"
        },
        {
            "name": "minFrequency",
            "baseName": "minFrequency",
            "type": "number"
        },
        {
            "name": "maxFrequency",
            "baseName": "maxFrequency",
            "type": "number"
        },
        {
            "name": "itemCount",
            "baseName": "itemCount",
            "type": "number"
        },
        {
            "name": "isTimeseries",
            "baseName": "isTimeseries",
            "type": "boolean"
        },
        {
            "name": "isFeatures",
            "baseName": "isFeatures",
            "type": "boolean"
        },
        {
            "name": "metadataFilterOptions",
            "baseName": "metadataFilterOptions",
            "type": "MetadataFilterOptions"
        },
        {
            "name": "labelsCount",
            "baseName": "labelsCount",
            "type": "number"
        },
        {
            "name": "minLabel",
            "baseName": "minLabel",
            "type": "number"
        },
        {
            "name": "maxLabel",
            "baseName": "maxLabel",
            "type": "number"
        },
        {
            "name": "valueGroups",
            "baseName": "valueGroups",
            "type": "Array<RawDataLabelDistributionRegressionValueGroup>"
        },
        {
            "name": "groupsPerLabelMapKey",
            "baseName": "groupsPerLabelMapKey",
            "type": "{ [key: string]: RawDataLabelDistributionRegressionValueGroupsPerKey; }"
        }    ];

    static getAttributeTypeMap() {
        return ProjectDatasetMetadataRegressionCategory.attributeTypeMap;
    }
}


export type ProjectDatasetMetadataRegressionCategoryTypeEnum = 'regression';
export const ProjectDatasetMetadataRegressionCategoryTypeEnumValues: string[] = ['regression'];
