/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ModelEngineShortEnum } from './modelEngineShortEnum';

export class ProjectInfoResponseAllOfDeploySettings {
    'eonCompiler': boolean;
    'sensor': ProjectInfoResponseAllOfDeploySettingsSensorEnum;
    'arduinoLibraryName': string;
    'tinkergenLibraryName': string;
    'particleLibraryName': string;
    'lastDeployModelEngine'?: ModelEngineShortEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "eonCompiler",
            "baseName": "eonCompiler",
            "type": "boolean"
        },
        {
            "name": "sensor",
            "baseName": "sensor",
            "type": "ProjectInfoResponseAllOfDeploySettingsSensorEnum"
        },
        {
            "name": "arduinoLibraryName",
            "baseName": "arduinoLibraryName",
            "type": "string"
        },
        {
            "name": "tinkergenLibraryName",
            "baseName": "tinkergenLibraryName",
            "type": "string"
        },
        {
            "name": "particleLibraryName",
            "baseName": "particleLibraryName",
            "type": "string"
        },
        {
            "name": "lastDeployModelEngine",
            "baseName": "lastDeployModelEngine",
            "type": "ModelEngineShortEnum"
        }    ];

    static getAttributeTypeMap() {
        return ProjectInfoResponseAllOfDeploySettings.attributeTypeMap;
    }
}


export type ProjectInfoResponseAllOfDeploySettingsSensorEnum = 'accelerometer' | 'microphone' | 'camera' | 'positional' | 'environmental' | 'fusion' | 'unknown';
export const ProjectInfoResponseAllOfDeploySettingsSensorEnumValues: string[] = ['accelerometer', 'microphone', 'camera', 'positional', 'environmental', 'fusion', 'unknown'];
