// Generated by studio/openapi/generate-models/convert.ts

export type RawDataLabelDistributionLabel = {
    label: string;
    /**
    * Total sample length for the label in milliseconds. For data types without a duration-based total this may be 0.
    */
    totalLength: number;
    /**
    * Total sample length for the label given as a UI-friendly formatted string.
    */
    totalLengthStr: string;
    /**
    * Total sample data count for the label.
    */
    dataCount: number;
};
