// Generated by studio/openapi/generate-models/convert.ts

import type { DeployPretrainedModelInputTimeSeries } from './deployPretrainedModelInputTimeSeries';
import type { DeployPretrainedModelInputAudio } from './deployPretrainedModelInputAudio';
import type { DeployPretrainedModelInputImage } from './deployPretrainedModelInputImage';
import type { DeployPretrainedModelInputOther } from './deployPretrainedModelInputOther';
import type { DeployPretrainedModelModelClassification } from './deployPretrainedModelModelClassification';
import type { DeployPretrainedModelModelRegression } from './deployPretrainedModelModelRegression';
import type { DeployPretrainedModelModelObjectDetection } from './deployPretrainedModelModelObjectDetection';
import type { DeployPretrainedModelModelFreeform } from './deployPretrainedModelModelFreeform';
import type { DeployPretrainedModelModelAnomaly } from './deployPretrainedModelModelAnomaly';
import type { DeployPretrainedModelModelVisualAnomaly } from './deployPretrainedModelModelVisualAnomaly';

export type SavePretrainedModelRequest = {
    input: DeployPretrainedModelInputTimeSeries
        | DeployPretrainedModelInputAudio
        | DeployPretrainedModelInputImage
        | DeployPretrainedModelInputOther;
    model: DeployPretrainedModelModelClassification
        | DeployPretrainedModelModelRegression
        | DeployPretrainedModelModelObjectDetection
        | DeployPretrainedModelModelFreeform
        | DeployPretrainedModelModelAnomaly
        | DeployPretrainedModelModelVisualAnomaly;
};
