/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class SetImpulseThresholdsRequestThresholds {
    /**
    * Learn block ID for which you want to set the threshold
    */
    'blockId': number;
    /**
    * Threshold identifier (see BlockThreshold#key)
    */
    'key': string;
    /**
    * New threshold value
    */
    'value': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "blockId",
            "baseName": "blockId",
            "type": "number"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SetImpulseThresholdsRequestThresholds.attributeTypeMap;
    }
}

