// Generated by studio/openapi/generate-models/convert.ts

export type StartDeviceSnapshotDebugStreamRequest = {
    resolution: StartDeviceSnapshotDebugStreamRequestResolutionEnum;
};

export type StartDeviceSnapshotDebugStreamRequestResolutionEnum = 'high' | 'low';
export const StartDeviceSnapshotDebugStreamRequestResolutionEnumValues: string[] = [ 'high', 'low' ];
