// Generated by studio/openapi/generate-models/convert.ts

import type { KerasModelVariantEnum } from './kerasModelVariantEnum';

export type StartClassifyJobRequest = {
    /**
    * Set of model variants to run the classify job against.
    */
    modelVariants?: KerasModelVariantEnum[];
    /**
    * If enabled, skips feature generation altogether. Used e.g. if you update thresholds.
    */
    skipFeatureGeneration?: boolean;
};
