// Generated by studio/openapi/generate-models/convert.ts

import type { ApplicationBudget } from './applicationBudget';
import type { TargetConstraintsDevice } from './targetConstraintsDevice';

export type TargetConstraints = {
    /**
    * A type explaining how the target was chosen. If updating this manually, use the 'user-configured' type
    */
    selectedTargetBasedOn?: TargetConstraintsSelectedTargetBasedOnEnum;
    /**
    * The potential targets for the project, where each entry captures hardware attributes that allow target guidance
    * throughout the Studio workflow. The first target in the list is considered as the selected target for the project.
    */
    targetDevices: TargetConstraintsDevice[];
    /**
    * A list of application budgets to be configured based on target device. An application budget enables guidance on
    * performance and resource usage. The first application budget in the list is considered as the selected budget for
    * the project.
    */
    applicationBudgets: ApplicationBudget[];
};

export type TargetConstraintsSelectedTargetBasedOnEnum = 'user-configured' | 'default' | 'default-accepted' | 'recent-project' | 'connected-device';
export const TargetConstraintsSelectedTargetBasedOnEnumValues: string[] = [ 'user-configured', 'default', 'default-accepted', 'recent-project', 'connected-device' ];
