// Generated by studio/openapi/generate-models/convert.ts

import type { TargetProcessor } from './targetProcessor';

export type TargetConstraintsDevice = {
    /**
    * Target processors
    */
    processors?: TargetProcessor[];
    /**
    * The exact dev board part number, if available
    */
    board?: string;
    /**
    * Display name in Studio
    */
    name?: string;
    /**
    * MCU identifier, if available
    */
    latencyDevice?: string;
};
