// Generated by studio/openapi/generate-models/convert.ts

import type { JobStatus } from './jobStatus';
import type { TunerSpaceImpulse } from './tunerSpaceImpulse';

export type TunerRun = {
    tunerJobId: number;
    tunerCoordinatorJobId: number;
    index: number;
    name?: string;
    created: Date;
    jobStatus: JobStatus;
    continuationJobId?: number;
    /**
    * List of impulses specifying the EON Tuner search space
    */
    space?: TunerSpaceImpulse[];
    /**
    * Whether the run is visible in the UI
    */
    visible: boolean;
};
