/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BlockType } from './blockType';
import { DSPGroupItem } from './dSPGroupItem';
import { TunerBlockVariants } from './tunerBlockVariants';

export class TunerBlock {
    'type': string;
    'title': string;
    'blockType': BlockType;
    'author'?: string;
    'description'?: string;
    'name'?: string;
    'recommended'?: boolean;
    'organizationModelId'?: number;
    'params'?: { [key: string]: DSPGroupItem; };
    'defaultConfig'?: object;
    'variants'?: { [key: string]: TunerBlockVariants; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "blockType",
            "baseName": "blockType",
            "type": "BlockType"
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "recommended",
            "baseName": "recommended",
            "type": "boolean"
        },
        {
            "name": "organizationModelId",
            "baseName": "organizationModelId",
            "type": "number"
        },
        {
            "name": "params",
            "baseName": "params",
            "type": "{ [key: string]: DSPGroupItem; }"
        },
        {
            "name": "defaultConfig",
            "baseName": "defaultConfig",
            "type": "object"
        },
        {
            "name": "variants",
            "baseName": "variants",
            "type": "{ [key: string]: TunerBlockVariants; }"
        }    ];

    static getAttributeTypeMap() {
        return TunerBlock.attributeTypeMap;
    }
}

