// Generated by studio/openapi/generate-models/convert.ts

/**
* The type of in-product guided tutorial to show in the getting started wizard
*/

export type TutorialType = 'kws' | 'cv';
export const TutorialTypeValues: string[] = [ 'kws', 'cv' ];
