/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* The type of in-product guided tutorial to show in the getting started wizard
*/

export type TutorialType = 'kws' | 'cv';
export const TutorialTypeValues: string[] = ['kws', 'cv'];
