// Generated by studio/openapi/generate-models/convert.ts

export type UpdateWhitelabelLearningBlocksRequest = {
    /**
    * The types of the learning blocks that are enabled for this whitelabel.
    */
    learningBlocks?: string[];
};
