// Generated by studio/openapi/generate-models/convert.ts

import type { UserProjectsSortOrder } from './userProjectsSortOrder';

/**
* Only fields set in this object will be updated.
*/
export type UpdateUserRequest = {
    /**
    * New full name
    */
    name?: string;
    /**
    * New job title
    */
    jobTitle?: string;
    /**
    * New company name
    */
    companyName?: string;
    /**
    * List of user experiments
    */
    experiments?: string[];
    projectsSortOrder?: UserProjectsSortOrder;
    /**
    * User timezone.
    */
    timezone?: string;
};
