// Generated by studio/openapi/generate-models/convert.ts

/**
* Only fields set in this object will be updated.
*/
export type UpdateThemeLogosRequest = {
    /**
    * Primary logo URL
    */
    primary?: string;
    /**
    * Primary logo for dark background URL
    */
    primaryWhite?: string;
    /**
    * Login logo URL
    */
    login?: string;
    /**
    * Login logo for dark background URL
    */
    loginWhite?: string;
    /**
    * Mark URL
    */
    mark?: string;
    /**
    * Mark for dark background URL
    */
    markWhite?: string;
    /**
    * Device logo URL
    */
    deviceLogo?: string;
};
