/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class UserSetTotpMfaKeyResponseAllOf {
    /**
    * 10 recovery codes, which can be used in case you\'ve lost access to your MFA TOTP app. Recovery codes are single use. Once you\'ve used a recovery code once, it can not be used again.
    */
    'recoveryCodes': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "recoveryCodes",
            "baseName": "recoveryCodes",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return UserSetTotpMfaKeyResponseAllOf.attributeTypeMap;
    }
}

