// Generated by studio/openapi/generate-models/convert.ts

export type UserSetTotpMfaKeyRequest = {
    /**
    * Secret key obtained through `userGenerateNewMfaKey`.
    */
    key: string;
    /**
    * TOTP token that is valid for the key (to ensure the device is configured correctly)
    */
    totpToken: string;
};
