// Generated by studio/openapi/generate-models/convert.ts

import type { VlmModel } from './vlmModel';

export type VlmGetModelResponse = {
    /**
    * Whether the operation succeeded
    */
    success: boolean;
    /**
    * Optional error description (set if 'success' was false)
    */
    error?: string;
    model?: VlmModel;
};
