// Generated by studio/openapi/generate-models/convert.ts

import type { VlmInferenceResultsResults } from './vlmInferenceResultsResults';

export type VlmInferenceResults = {
    /**
    * VLM config ID associated with these results
    */
    configId: number;
    results: VlmInferenceResultsResults[];
};
