// Generated by studio/openapi/generate-models/convert.ts

export type WhitelabelAdminCreateOrganizationRequest = {
    /**
    * The name of the organization.
    */
    organizationName: string;
    /**
    * Unique identifier of the administrator of the new organization.
    */
    adminId?: number;
    /**
    * Email of the administrator of the new organization.
    */
    adminEmail?: string;
};
