/**
 * Edge Impulse API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

const PATH = require('path');
module.paths.push(PATH.join(process.cwd(), 'node_modules'));

import type { fetch as UndiciFetch, FormData as UndiciFormData, Response as UndiciResponse } from 'undici-types';

let fetch: typeof globalThis.fetch | typeof UndiciFetch;
let FormData: typeof globalThis.FormData | typeof UndiciFormData;

if (globalThis.fetch && globalThis.FormData) {
    fetch = globalThis.fetch;
    FormData = globalThis.FormData;
}
else {
    const undici = require('undici');
    fetch = undici.fetch;
    FormData = undici.FormData;
}

import { CreateThirdPartyAuthRequest } from '../model/createThirdPartyAuthRequest';
import { CreateThirdPartyAuthResponse } from '../model/createThirdPartyAuthResponse';
import { CreateUserThirdPartyRequest } from '../model/createUserThirdPartyRequest';
import { CreateUserThirdPartyResponse } from '../model/createUserThirdPartyResponse';
import { GenericApiResponse } from '../model/genericApiResponse';
import { GetAllThirdPartyAuthResponse } from '../model/getAllThirdPartyAuthResponse';
import { GetThirdPartyAuthResponse } from '../model/getThirdPartyAuthResponse';
import { UpdateThirdPartyAuthRequest } from '../model/updateThirdPartyAuthRequest';

import { ObjectSerializer, Authentication, VoidAuth, RequestOptionsType } from '../model/models';
import { HttpBasicAuth, ApiKeyAuth, OAuth } from '../model/models';

import { HttpError, RequestFile } from './apis';

let defaultBasePath = 'https://studio.edgeimpulse.com/v1';

async function parseResponse(res: Response | UndiciResponse): Promise<any> {
    const ct = (res.headers.get('content-type') || '').toLowerCase();

    if (ct.includes('application/json')) return res.json();

    if (/^(image|video|audio)\/|application\/(octet-stream|zip|x-tar|cbor)/.test(ct)) {
        return Buffer.from(await res.arrayBuffer());
    }

    return res.text();
}

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum ThirdPartyAuthApiApiKeys {
    ApiKeyAuthentication,
    JWTAuthentication,
    JWTHttpHeaderAuthentication,
}

export type authorizeThirdPartyFormParams = {
    nextUrl: string,
};


export type ThirdPartyAuthApiOpts = {
    extraHeaders?: Record<string, string>;
};

export class ThirdPartyAuthApi {
    protected _basePath = defaultBasePath;
    protected defaultHeaders : Record<string, string> = {};
    protected _opts : ThirdPartyAuthApiOpts = { };

    protected authentications = {
        'default': <Authentication>new VoidAuth(),
        'ApiKeyAuthentication': new ApiKeyAuth('header', 'x-api-key'),
        'OAuth2': new OAuth(),
        'JWTAuthentication': new ApiKeyAuth('cookie', 'jwt'),
        'JWTHttpHeaderAuthentication': new ApiKeyAuth('header', 'x-jwt-token'),
    }

    protected async handleResponse(response: Response | UndiciResponse, returnType: string | undefined): Promise<any> {
        let body = await parseResponse(response);
        if (!response.ok) {
            let errorMsg;
            if (typeof body === 'object' && body !== null && 'error' in body) {
                errorMsg = body.error;
            } else {
                errorMsg = `Failed to call "${response.url}", returned ${response.status}: ` + (typeof body === 'string' ? body : JSON.stringify(body));
            }
            throw new Error(errorMsg);
        }

        if (returnType) {
            body = ObjectSerializer.deserialize(body, returnType);
        }

        if (typeof body.success === 'boolean' && !body.success) {
            const errString = `Failed to call "${response.url}", returned ${response.status}: ` + body.error;
            throw new Error(body.error || errString);
        }

        return body;
    }

    constructor(basePath?: string, opts?: ThirdPartyAuthApiOpts);
    constructor(basePathOrUsername: string, opts?: ThirdPartyAuthApiOpts, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }

        this.opts = opts ?? { };
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    get basePath() {
        return this._basePath;
    }

    set opts(opts: ThirdPartyAuthApiOpts) {
        this._opts = opts;
    }

    get opts() {
        return this._opts;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: ThirdPartyAuthApiApiKeys, value: string | undefined) {
        (this.authentications as any)[ThirdPartyAuthApiApiKeys[key]].apiKey = value;
    }

    set accessToken(token: string) {
        this.authentications.OAuth2.accessToken = token;
    }


    /**
     * Authorize a third party to access a project
     * @summary Give access to project
     * @param projectId Project ID
     * @param authId Auth ID
     * @param nextUrl The URL to redirect to after authorization is completed.
     */
    public async authorizeThirdParty (projectId: number, authId: number, params: authorizeThirdPartyFormParams, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<any> {
        const localVarPath = this.basePath + '/api/{projectId}/third-party-auth/{authId}/authorize'
            .replace('{' + 'projectId' + '}', encodeURIComponent(String(projectId)))
            .replace('{' + 'authId' + '}', encodeURIComponent(String(authId)));
        let localVarQueryParameters: Record<string, string> = {};
        let localVarHeaderParams: Record<string, string> = {
            'User-Agent': 'edgeimpulse-api nodejs',
            'Content-Type': 'application/json',
            ...this.defaultHeaders,
        };
        let localVarFormParams: Record<string, string> | FormData | UndiciFormData | undefined;

        // verify required parameter 'projectId' is not null or undefined


        if (projectId === null || projectId === undefined) {
            throw new Error('Required parameter projectId was null or undefined when calling authorizeThirdParty.');
        }

        // verify required parameter 'authId' is not null or undefined


        if (authId === null || authId === undefined) {
            throw new Error('Required parameter authId was null or undefined when calling authorizeThirdParty.');
        }

        // verify required parameter 'nextUrl' is not null or undefined
        if (params.nextUrl === null || params.nextUrl === undefined) {
            throw new Error('Required parameter params.nextUrl was null or undefined when calling authorizeThirdParty.');
        }



        localVarHeaderParams = {
            ...localVarHeaderParams,
            ...options.headers,
            ...this.opts.extraHeaders,
        };

        if (params.nextUrl !== undefined) {
            const isParametersField = ("nextUrl" as string) === "parameters";
            const serializableParams = isParametersField && params && ("parameters" in params);

            const nextUrlSerialized = serializableParams
                ? JSON.stringify((params as any).parameters)
                : ObjectSerializer.serializeFormData(params.nextUrl as any, "string");

            if (localVarFormParams instanceof FormData) {
                (localVarFormParams as FormData).append('nextUrl', nextUrlSerialized);
            }
            else {
                if (!localVarFormParams) {
                    localVarFormParams = {};
                }
                (localVarFormParams as Record<string, string>)['nextUrl'] = nextUrlSerialized;
            }
        }
        const queryString = Object.entries(localVarQueryParameters)
            .filter(([, value]) => value !== undefined)
            .map(([key, value]) => `${key}=${encodeURIComponent(String(value))}`)
            .join('&');

        let localVarUrl = localVarPath + (queryString ? `?${queryString}` : '');
        let localVarRequestOptions: RequestOptionsType = {
            method: 'POST',
            headers: { ...localVarHeaderParams },
        };


        let requestOptions = localVarRequestOptions;
        let url = localVarUrl;
        const auth_ApiKeyAuthentication = await this.authentications.ApiKeyAuthentication.applyToRequest(requestOptions, url);
        requestOptions = auth_ApiKeyAuthentication.requestOptions;
        url = auth_ApiKeyAuthentication.url;

        const auth_JWTAuthentication = await this.authentications.JWTAuthentication.applyToRequest(requestOptions, url);
        requestOptions = auth_JWTAuthentication.requestOptions;
        url = auth_JWTAuthentication.url;

        const auth_JWTHttpHeaderAuthentication = await this.authentications.JWTHttpHeaderAuthentication.applyToRequest(requestOptions, url);
        requestOptions = auth_JWTHttpHeaderAuthentication.requestOptions;
        url = auth_JWTHttpHeaderAuthentication.url;

        const auth_OAuth2 = await this.authentications.OAuth2.applyToRequest(requestOptions, url);
        requestOptions = auth_OAuth2.requestOptions;
        url = auth_OAuth2.url;

        const authDefault = await this.authentications.default.applyToRequest(requestOptions, url);
        requestOptions = authDefault.requestOptions;
        url = authDefault.url;

        if (localVarFormParams) {
            delete requestOptions.headers['Content-Type'];
            if (localVarFormParams instanceof FormData) {
                // FormData: fetch will handle Content-Type automatically.
                requestOptions.body = localVarFormParams;
            }
            else if (Object.keys(localVarFormParams).length > 0) {
                // URL-encoded form
                requestOptions.body = new URLSearchParams(localVarFormParams as Record<string, string>).toString();
                requestOptions.headers['Content-Type'] = 'application/x-www-form-urlencoded';
            }
        }

        const response = await fetch(url, requestOptions);
        return this.handleResponse(
            response,
            undefined
        );
    }

    /**
     * Create a new third party authentication partner
     * @summary Create third party auth
     * @param createThirdPartyAuthRequest 
     */
    public async createThirdPartyAuth (createThirdPartyAuthRequest: CreateThirdPartyAuthRequest, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<CreateThirdPartyAuthResponse> {
        const localVarPath = this.basePath + '/api/third-party-auth';
        let localVarQueryParameters: Record<string, string> = {};
        let localVarHeaderParams: Record<string, string> = {
            'User-Agent': 'edgeimpulse-api nodejs',
            'Content-Type': 'application/json',
            ...this.defaultHeaders,
        };
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: Record<string, string> | FormData | UndiciFormData | undefined;

        // verify required parameter 'createThirdPartyAuthRequest' is not null or undefined


        if (createThirdPartyAuthRequest === null || createThirdPartyAuthRequest === undefined) {
            throw new Error('Required parameter createThirdPartyAuthRequest was null or undefined when calling createThirdPartyAuth.');
        }

        localVarHeaderParams = {
            ...localVarHeaderParams,
            ...options.headers,
            ...this.opts.extraHeaders,
        };

        const queryString = Object.entries(localVarQueryParameters)
            .filter(([, value]) => value !== undefined)
            .map(([key, value]) => `${key}=${encodeURIComponent(String(value))}`)
            .join('&');

        let localVarUrl = localVarPath + (queryString ? `?${queryString}` : '');
        let localVarRequestOptions: RequestOptionsType = {
            method: 'POST',
            headers: { ...localVarHeaderParams },
        };

        localVarRequestOptions.body = JSON.stringify(ObjectSerializer.serialize(createThirdPartyAuthRequest, "CreateThirdPartyAuthRequest"));


        let requestOptions = localVarRequestOptions;
        let url = localVarUrl;
        const auth_ApiKeyAuthentication = await this.authentications.ApiKeyAuthentication.applyToRequest(requestOptions, url);
        requestOptions = auth_ApiKeyAuthentication.requestOptions;
        url = auth_ApiKeyAuthentication.url;

        const auth_JWTAuthentication = await this.authentications.JWTAuthentication.applyToRequest(requestOptions, url);
        requestOptions = auth_JWTAuthentication.requestOptions;
        url = auth_JWTAuthentication.url;

        const auth_JWTHttpHeaderAuthentication = await this.authentications.JWTHttpHeaderAuthentication.applyToRequest(requestOptions, url);
        requestOptions = auth_JWTHttpHeaderAuthentication.requestOptions;
        url = auth_JWTHttpHeaderAuthentication.url;

        const auth_OAuth2 = await this.authentications.OAuth2.applyToRequest(requestOptions, url);
        requestOptions = auth_OAuth2.requestOptions;
        url = auth_OAuth2.url;

        const authDefault = await this.authentications.default.applyToRequest(requestOptions, url);
        requestOptions = authDefault.requestOptions;
        url = authDefault.url;

        if (localVarFormParams) {
            delete requestOptions.headers['Content-Type'];
            if (localVarFormParams instanceof FormData) {
                // FormData: fetch will handle Content-Type automatically.
                requestOptions.body = localVarFormParams;
            }
            else if (Object.keys(localVarFormParams).length > 0) {
                // URL-encoded form
                requestOptions.body = new URLSearchParams(localVarFormParams as Record<string, string>).toString();
                requestOptions.headers['Content-Type'] = 'application/x-www-form-urlencoded';
            }
        }

        const response = await fetch(url, requestOptions);
        return this.handleResponse(
            response,
            'CreateThirdPartyAuthResponse'
        );
    }

    /**
     * Login as a user as a third-party authentication provider. If the user does not exists, it\'s automatically created. You can only log in as users that were previously created by you.
     * @summary Create or login a user
     * @param authId Auth ID
     * @param createUserThirdPartyRequest 
     */
    public async createUserThirdParty (authId: number, createUserThirdPartyRequest: CreateUserThirdPartyRequest, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<CreateUserThirdPartyResponse> {
        const localVarPath = this.basePath + '/api/third-party-auth/{authId}/login'
            .replace('{' + 'authId' + '}', encodeURIComponent(String(authId)));
        let localVarQueryParameters: Record<string, string> = {};
        let localVarHeaderParams: Record<string, string> = {
            'User-Agent': 'edgeimpulse-api nodejs',
            'Content-Type': 'application/json',
            ...this.defaultHeaders,
        };
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: Record<string, string> | FormData | UndiciFormData | undefined;

        // verify required parameter 'authId' is not null or undefined


        if (authId === null || authId === undefined) {
            throw new Error('Required parameter authId was null or undefined when calling createUserThirdParty.');
        }

        // verify required parameter 'createUserThirdPartyRequest' is not null or undefined


        if (createUserThirdPartyRequest === null || createUserThirdPartyRequest === undefined) {
            throw new Error('Required parameter createUserThirdPartyRequest was null or undefined when calling createUserThirdParty.');
        }

        localVarHeaderParams = {
            ...localVarHeaderParams,
            ...options.headers,
            ...this.opts.extraHeaders,
        };

        const queryString = Object.entries(localVarQueryParameters)
            .filter(([, value]) => value !== undefined)
            .map(([key, value]) => `${key}=${encodeURIComponent(String(value))}`)
            .join('&');

        let localVarUrl = localVarPath + (queryString ? `?${queryString}` : '');
        let localVarRequestOptions: RequestOptionsType = {
            method: 'POST',
            headers: { ...localVarHeaderParams },
        };

        localVarRequestOptions.body = JSON.stringify(ObjectSerializer.serialize(createUserThirdPartyRequest, "CreateUserThirdPartyRequest"));


        let requestOptions = localVarRequestOptions;
        let url = localVarUrl;
        const auth_ApiKeyAuthentication = await this.authentications.ApiKeyAuthentication.applyToRequest(requestOptions, url);
        requestOptions = auth_ApiKeyAuthentication.requestOptions;
        url = auth_ApiKeyAuthentication.url;

        const auth_JWTAuthentication = await this.authentications.JWTAuthentication.applyToRequest(requestOptions, url);
        requestOptions = auth_JWTAuthentication.requestOptions;
        url = auth_JWTAuthentication.url;

        const auth_JWTHttpHeaderAuthentication = await this.authentications.JWTHttpHeaderAuthentication.applyToRequest(requestOptions, url);
        requestOptions = auth_JWTHttpHeaderAuthentication.requestOptions;
        url = auth_JWTHttpHeaderAuthentication.url;

        const auth_OAuth2 = await this.authentications.OAuth2.applyToRequest(requestOptions, url);
        requestOptions = auth_OAuth2.requestOptions;
        url = auth_OAuth2.url;

        const authDefault = await this.authentications.default.applyToRequest(requestOptions, url);
        requestOptions = authDefault.requestOptions;
        url = authDefault.url;

        if (localVarFormParams) {
            delete requestOptions.headers['Content-Type'];
            if (localVarFormParams instanceof FormData) {
                // FormData: fetch will handle Content-Type automatically.
                requestOptions.body = localVarFormParams;
            }
            else if (Object.keys(localVarFormParams).length > 0) {
                // URL-encoded form
                requestOptions.body = new URLSearchParams(localVarFormParams as Record<string, string>).toString();
                requestOptions.headers['Content-Type'] = 'application/x-www-form-urlencoded';
            }
        }

        const response = await fetch(url, requestOptions);
        return this.handleResponse(
            response,
            'CreateUserThirdPartyResponse'
        );
    }

    /**
     * Delete a third party authentication partner
     * @summary Delete third party auth
     * @param authId Auth ID
     */
    public async deleteThirdPartyAuth (authId: number, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<GenericApiResponse> {
        const localVarPath = this.basePath + '/api/third-party-auth/{authId}'
            .replace('{' + 'authId' + '}', encodeURIComponent(String(authId)));
        let localVarQueryParameters: Record<string, string> = {};
        let localVarHeaderParams: Record<string, string> = {
            'User-Agent': 'edgeimpulse-api nodejs',
            'Content-Type': 'application/json',
            ...this.defaultHeaders,
        };
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: Record<string, string> | FormData | UndiciFormData | undefined;

        // verify required parameter 'authId' is not null or undefined


        if (authId === null || authId === undefined) {
            throw new Error('Required parameter authId was null or undefined when calling deleteThirdPartyAuth.');
        }

        localVarHeaderParams = {
            ...localVarHeaderParams,
            ...options.headers,
            ...this.opts.extraHeaders,
        };

        const queryString = Object.entries(localVarQueryParameters)
            .filter(([, value]) => value !== undefined)
            .map(([key, value]) => `${key}=${encodeURIComponent(String(value))}`)
            .join('&');

        let localVarUrl = localVarPath + (queryString ? `?${queryString}` : '');
        let localVarRequestOptions: RequestOptionsType = {
            method: 'DELETE',
            headers: { ...localVarHeaderParams },
        };


        let requestOptions = localVarRequestOptions;
        let url = localVarUrl;
        const auth_ApiKeyAuthentication = await this.authentications.ApiKeyAuthentication.applyToRequest(requestOptions, url);
        requestOptions = auth_ApiKeyAuthentication.requestOptions;
        url = auth_ApiKeyAuthentication.url;

        const auth_JWTAuthentication = await this.authentications.JWTAuthentication.applyToRequest(requestOptions, url);
        requestOptions = auth_JWTAuthentication.requestOptions;
        url = auth_JWTAuthentication.url;

        const auth_JWTHttpHeaderAuthentication = await this.authentications.JWTHttpHeaderAuthentication.applyToRequest(requestOptions, url);
        requestOptions = auth_JWTHttpHeaderAuthentication.requestOptions;
        url = auth_JWTHttpHeaderAuthentication.url;

        const auth_OAuth2 = await this.authentications.OAuth2.applyToRequest(requestOptions, url);
        requestOptions = auth_OAuth2.requestOptions;
        url = auth_OAuth2.url;

        const authDefault = await this.authentications.default.applyToRequest(requestOptions, url);
        requestOptions = authDefault.requestOptions;
        url = authDefault.url;

        if (localVarFormParams) {
            delete requestOptions.headers['Content-Type'];
            if (localVarFormParams instanceof FormData) {
                // FormData: fetch will handle Content-Type automatically.
                requestOptions.body = localVarFormParams;
            }
            else if (Object.keys(localVarFormParams).length > 0) {
                // URL-encoded form
                requestOptions.body = new URLSearchParams(localVarFormParams as Record<string, string>).toString();
                requestOptions.headers['Content-Type'] = 'application/x-www-form-urlencoded';
            }
        }

        const response = await fetch(url, requestOptions);
        return this.handleResponse(
            response,
            'GenericApiResponse'
        );
    }

    /**
     * Get information about all third party authentication partners
     * @summary Get all third party auth
     */
    public async getAllThirdPartyAuth (options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<GetAllThirdPartyAuthResponse> {
        const localVarPath = this.basePath + '/api/third-party-auth';
        let localVarQueryParameters: Record<string, string> = {};
        let localVarHeaderParams: Record<string, string> = {
            'User-Agent': 'edgeimpulse-api nodejs',
            'Content-Type': 'application/json',
            ...this.defaultHeaders,
        };
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: Record<string, string> | FormData | UndiciFormData | undefined;

        localVarHeaderParams = {
            ...localVarHeaderParams,
            ...options.headers,
            ...this.opts.extraHeaders,
        };

        const queryString = Object.entries(localVarQueryParameters)
            .filter(([, value]) => value !== undefined)
            .map(([key, value]) => `${key}=${encodeURIComponent(String(value))}`)
            .join('&');

        let localVarUrl = localVarPath + (queryString ? `?${queryString}` : '');
        let localVarRequestOptions: RequestOptionsType = {
            method: 'GET',
            headers: { ...localVarHeaderParams },
        };


        let requestOptions = localVarRequestOptions;
        let url = localVarUrl;
        const auth_ApiKeyAuthentication = await this.authentications.ApiKeyAuthentication.applyToRequest(requestOptions, url);
        requestOptions = auth_ApiKeyAuthentication.requestOptions;
        url = auth_ApiKeyAuthentication.url;

        const auth_JWTAuthentication = await this.authentications.JWTAuthentication.applyToRequest(requestOptions, url);
        requestOptions = auth_JWTAuthentication.requestOptions;
        url = auth_JWTAuthentication.url;

        const auth_JWTHttpHeaderAuthentication = await this.authentications.JWTHttpHeaderAuthentication.applyToRequest(requestOptions, url);
        requestOptions = auth_JWTHttpHeaderAuthentication.requestOptions;
        url = auth_JWTHttpHeaderAuthentication.url;

        const auth_OAuth2 = await this.authentications.OAuth2.applyToRequest(requestOptions, url);
        requestOptions = auth_OAuth2.requestOptions;
        url = auth_OAuth2.url;

        const authDefault = await this.authentications.default.applyToRequest(requestOptions, url);
        requestOptions = authDefault.requestOptions;
        url = authDefault.url;

        if (localVarFormParams) {
            delete requestOptions.headers['Content-Type'];
            if (localVarFormParams instanceof FormData) {
                // FormData: fetch will handle Content-Type automatically.
                requestOptions.body = localVarFormParams;
            }
            else if (Object.keys(localVarFormParams).length > 0) {
                // URL-encoded form
                requestOptions.body = new URLSearchParams(localVarFormParams as Record<string, string>).toString();
                requestOptions.headers['Content-Type'] = 'application/x-www-form-urlencoded';
            }
        }

        const response = await fetch(url, requestOptions);
        return this.handleResponse(
            response,
            'GetAllThirdPartyAuthResponse'
        );
    }

    /**
     * Get information about a third party authentication partner
     * @summary Get third party auth
     * @param authId Auth ID
     */
    public async getThirdPartyAuth (authId: number, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<GetThirdPartyAuthResponse> {
        const localVarPath = this.basePath + '/api/third-party-auth/{authId}'
            .replace('{' + 'authId' + '}', encodeURIComponent(String(authId)));
        let localVarQueryParameters: Record<string, string> = {};
        let localVarHeaderParams: Record<string, string> = {
            'User-Agent': 'edgeimpulse-api nodejs',
            'Content-Type': 'application/json',
            ...this.defaultHeaders,
        };
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: Record<string, string> | FormData | UndiciFormData | undefined;

        // verify required parameter 'authId' is not null or undefined


        if (authId === null || authId === undefined) {
            throw new Error('Required parameter authId was null or undefined when calling getThirdPartyAuth.');
        }

        localVarHeaderParams = {
            ...localVarHeaderParams,
            ...options.headers,
            ...this.opts.extraHeaders,
        };

        const queryString = Object.entries(localVarQueryParameters)
            .filter(([, value]) => value !== undefined)
            .map(([key, value]) => `${key}=${encodeURIComponent(String(value))}`)
            .join('&');

        let localVarUrl = localVarPath + (queryString ? `?${queryString}` : '');
        let localVarRequestOptions: RequestOptionsType = {
            method: 'GET',
            headers: { ...localVarHeaderParams },
        };


        let requestOptions = localVarRequestOptions;
        let url = localVarUrl;
        const auth_ApiKeyAuthentication = await this.authentications.ApiKeyAuthentication.applyToRequest(requestOptions, url);
        requestOptions = auth_ApiKeyAuthentication.requestOptions;
        url = auth_ApiKeyAuthentication.url;

        const auth_JWTAuthentication = await this.authentications.JWTAuthentication.applyToRequest(requestOptions, url);
        requestOptions = auth_JWTAuthentication.requestOptions;
        url = auth_JWTAuthentication.url;

        const auth_JWTHttpHeaderAuthentication = await this.authentications.JWTHttpHeaderAuthentication.applyToRequest(requestOptions, url);
        requestOptions = auth_JWTHttpHeaderAuthentication.requestOptions;
        url = auth_JWTHttpHeaderAuthentication.url;

        const auth_OAuth2 = await this.authentications.OAuth2.applyToRequest(requestOptions, url);
        requestOptions = auth_OAuth2.requestOptions;
        url = auth_OAuth2.url;

        const authDefault = await this.authentications.default.applyToRequest(requestOptions, url);
        requestOptions = authDefault.requestOptions;
        url = authDefault.url;

        if (localVarFormParams) {
            delete requestOptions.headers['Content-Type'];
            if (localVarFormParams instanceof FormData) {
                // FormData: fetch will handle Content-Type automatically.
                requestOptions.body = localVarFormParams;
            }
            else if (Object.keys(localVarFormParams).length > 0) {
                // URL-encoded form
                requestOptions.body = new URLSearchParams(localVarFormParams as Record<string, string>).toString();
                requestOptions.headers['Content-Type'] = 'application/x-www-form-urlencoded';
            }
        }

        const response = await fetch(url, requestOptions);
        return this.handleResponse(
            response,
            'GetThirdPartyAuthResponse'
        );
    }

    /**
     * Update a third party authentication partner
     * @summary Update third party auth
     * @param authId Auth ID
     * @param updateThirdPartyAuthRequest 
     */
    public async updateThirdPartyAuth (authId: number, updateThirdPartyAuthRequest: UpdateThirdPartyAuthRequest, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<GenericApiResponse> {
        const localVarPath = this.basePath + '/api/third-party-auth/{authId}'
            .replace('{' + 'authId' + '}', encodeURIComponent(String(authId)));
        let localVarQueryParameters: Record<string, string> = {};
        let localVarHeaderParams: Record<string, string> = {
            'User-Agent': 'edgeimpulse-api nodejs',
            'Content-Type': 'application/json',
            ...this.defaultHeaders,
        };
        const produces = ['application/json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: Record<string, string> | FormData | UndiciFormData | undefined;

        // verify required parameter 'authId' is not null or undefined


        if (authId === null || authId === undefined) {
            throw new Error('Required parameter authId was null or undefined when calling updateThirdPartyAuth.');
        }

        // verify required parameter 'updateThirdPartyAuthRequest' is not null or undefined


        if (updateThirdPartyAuthRequest === null || updateThirdPartyAuthRequest === undefined) {
            throw new Error('Required parameter updateThirdPartyAuthRequest was null or undefined when calling updateThirdPartyAuth.');
        }

        localVarHeaderParams = {
            ...localVarHeaderParams,
            ...options.headers,
            ...this.opts.extraHeaders,
        };

        const queryString = Object.entries(localVarQueryParameters)
            .filter(([, value]) => value !== undefined)
            .map(([key, value]) => `${key}=${encodeURIComponent(String(value))}`)
            .join('&');

        let localVarUrl = localVarPath + (queryString ? `?${queryString}` : '');
        let localVarRequestOptions: RequestOptionsType = {
            method: 'POST',
            headers: { ...localVarHeaderParams },
        };

        localVarRequestOptions.body = JSON.stringify(ObjectSerializer.serialize(updateThirdPartyAuthRequest, "UpdateThirdPartyAuthRequest"));


        let requestOptions = localVarRequestOptions;
        let url = localVarUrl;
        const auth_ApiKeyAuthentication = await this.authentications.ApiKeyAuthentication.applyToRequest(requestOptions, url);
        requestOptions = auth_ApiKeyAuthentication.requestOptions;
        url = auth_ApiKeyAuthentication.url;

        const auth_JWTAuthentication = await this.authentications.JWTAuthentication.applyToRequest(requestOptions, url);
        requestOptions = auth_JWTAuthentication.requestOptions;
        url = auth_JWTAuthentication.url;

        const auth_JWTHttpHeaderAuthentication = await this.authentications.JWTHttpHeaderAuthentication.applyToRequest(requestOptions, url);
        requestOptions = auth_JWTHttpHeaderAuthentication.requestOptions;
        url = auth_JWTHttpHeaderAuthentication.url;

        const auth_OAuth2 = await this.authentications.OAuth2.applyToRequest(requestOptions, url);
        requestOptions = auth_OAuth2.requestOptions;
        url = auth_OAuth2.url;

        const authDefault = await this.authentications.default.applyToRequest(requestOptions, url);
        requestOptions = authDefault.requestOptions;
        url = authDefault.url;

        if (localVarFormParams) {
            delete requestOptions.headers['Content-Type'];
            if (localVarFormParams instanceof FormData) {
                // FormData: fetch will handle Content-Type automatically.
                requestOptions.body = localVarFormParams;
            }
            else if (Object.keys(localVarFormParams).length > 0) {
                // URL-encoded form
                requestOptions.body = new URLSearchParams(localVarFormParams as Record<string, string>).toString();
                requestOptions.headers['Content-Type'] = 'application/x-www-form-urlencoded';
            }
        }

        const response = await fetch(url, requestOptions);
        return this.handleResponse(
            response,
            'GenericApiResponse'
        );
    }
}
